// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as View$ReactNative from "reason-react-native/src/components/View.bs.js";
import * as ReactNativeReanimated from "react-native-reanimated";

var Extrapolate = { };

var Interpolation = { };

function setInitial(value, initialValue) {
  value.__Custom_InitialValue = initialValue;
  return value;
}

var Value = {
  Interpolation: Interpolation,
  setInitial: setInitial
};

var Clock = { };

var SpringUtils = { };

var InterpolatedValue = { };

var Event_defaultContentOffset = {
  y: undefined
};

var Event_defaultEvent = {
  translationX: undefined,
  velocityX: undefined,
  state: undefined,
  contentOffset: undefined,
  x: undefined
};

var $$Event = {
  defaultContentOffset: Event_defaultContentOffset,
  defaultEvent: Event_defaultEvent
};

function angle(angle$1) {
  return ReactNativeReanimated.default.concat(angle$1, "deg");
}

var StyleProp = {
  angle: angle
};

var make = ReactNativeReanimated.default.createAnimatedComponent(ReactNative.View);

var View = {
  make: make
};

export {
  Extrapolate ,
  Value ,
  Clock ,
  SpringUtils ,
  InterpolatedValue ,
  $$Event ,
  StyleProp ,
  View ,
  
}
/* make Not a pure module */
